### ISSUE TITLE
Errno19 ENODEV - lib/ds3231.py, line 211, in alarm1

### ISSUE THREAD

**Issue by kf0mlb** [hueyy/watchy_py#1]
I flashed my Watchy with the latest MicroPython, then used Thonny to upload your `src` to the board.  I renamed `secrets.example.py` to `secrets.py`, and added my wifi credentials.  When I did a `machine.reset()`, the board came back with:

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "uasyncio/core.py", line 1, in run
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "main.py", line 10, in main
  File "watchy.py", line 45, in __init__
  File "lib/ds3231.py", line 211, in alarm1
OSError: [Errno 19] ENODEV
MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32
```

Have you seen this error before?  I'm brand new to the ESP32/MicroPython game, so I apologize for the lack of further troubleshooting.

**Comment by hueyy** [comment]
ENODEV is a "no device" error. This seems to suggest your RTC module is
missing? It may be that the RTC module in your Watchy is different from
mine since Watchy changed the RTC module at some point. Check the Watchy
docs - you may need to modify my ds3231.py file or write some custom code
for your RTC module.

**Comment by kf0mlb** [comment]
I confirmed I have a v2 Watchy hardware, so I have the PCF8563 RTC.  I found a driver someone else wrote, so I will work on getting that working in my code.  Thank you!
